const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const vm=require('node:vm');const ts=require('typescript');
function load(file,mocks={}){const full=path.resolve(__dirname,'..',file);const module={exports:{}};const js=ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;vm.runInNewContext(js,{module,exports:module.exports,require:n=>n in mocks?mocks[n]:n.startsWith('@/')?load(n.slice(2)+'.ts',mocks):require(n),URL,console,process,Buffer,fetch,AbortSignal,Response,Error},{filename:full});return module.exports;}
const input={requestId:'12345678-1234-4234-8234-123456789abc',campaignId:'camp',contentItemId:'post',productName:'Actual guitar',productImage:'https://example.com/guitar.jpg',characterImage:'https://example.com/person.jpg',script:'Meet this guitar. Explore the details on our website.',duration:10,consent:true};
function fixture(overrides={}){let charged=0,calls=0,created=0;const prisma={job:{findFirst:async()=>null,update:async q=>({id:q.where.id,...q.data}),create:async q=>{created++;return{id:input.requestId,organizationId:'org',payload:q.data.payload,status:'starting'};}},campaign:{findFirst:async()=>({id:'camp',brandId:'brand'})},contentItem:{findFirst:async()=>({id:'post'})},subscription:{updateMany:async q=>{charged+=q.data.credits.decrement;return{count:1};},findUniqueOrThrow:async()=>({credits:1000})},creditLedger:{create:async()=>{}},...overrides};prisma.$transaction=async fn=>fn(prisma);const mocks={'next/server':{NextResponse:{json:(body,opts)=>({body,status:opts.status})}},'@/lib/auth/context':{tenantContext:async()=>({organizationId:'org',role:'owner'})},'@/lib/prisma':{prisma},'@/lib/http/errors':{apiError:()=>({status:500})},'@/lib/video/runway':{runwayConfigured:()=>true,validImage:x=>x.startsWith('https:'),createPresenterPortrait:async()=>{calls++;return{id:'portrait'};},RunwayError:class extends Error{}},'@/lib/presenter/jobs':{startPresenter:async job=>{calls++;return{...job,status:'running'};}},'@/lib/video/jobs':{videoSummary:j=>({id:j.id,status:j.status}),refreshVideo:async j=>j,failVideo:async()=>{}}};return{api:load('app/api/video/presenter/route.ts',mocks),counts:()=>({charged,calls,created})};}
const req=data=>({headers:new Headers(),json:async()=>data});
test('presenter costs distinguish duration and optional portrait',()=>{const plan=load('lib/presenter/plan.ts');assert.equal(plan.presenterCost(5,false),280);assert.equal(plan.presenterCost(10,true),536);assert.equal(plan.presenterCost(15,false),760);});
test('presenter generation charges once and saves to owned post',async()=>{const f=fixture();const r=await f.api.POST(req(input));assert.equal(r.status,202);assert.deepEqual(f.counts(),{charged:520,calls:1,created:1});assert.equal(r.body.job.contentItemId,'post');});
test('presenter retry retrieves existing task without charge or provider request',async()=>{const f=fixture({job:{findFirst:async()=>({id:input.requestId,payload:{mode:'presenter',campaignId:'camp',contentItemId:'post'},status:'running'})}});assert.equal((await f.api.POST(req(input))).status,200);assert.deepEqual(f.counts(),{charged:0,calls:0,created:0});});
test('presenter rejects unavailable campaign before any credit or generation',async()=>{const f=fixture({campaign:{findFirst:async()=>null}});assert.equal((await f.api.POST(req(input))).status,404);assert.deepEqual(f.counts(),{charged:0,calls:0,created:0});});
test('presenter requires explicit cost consent',async()=>{const f=fixture();assert.equal((await f.api.POST(req({...input,consent:false}))).status,400);assert.deepEqual(f.counts(),{charged:0,calls:0,created:0});});

test('fictional presenter includes portrait cost and records its task',async()=>{const f=fixture();const r=await f.api.POST(req({...input,characterImage:undefined}));assert.equal(r.status,202);assert.deepEqual(f.counts(),{charged:536,calls:1,created:1});});
test('presenter rejects a product belonging to another brand before spending',async()=>{const f=fixture({product:{findFirst:async q=>{assert.equal(q.where.brandId,'brand');return null;}}});assert.equal((await f.api.POST(req({...input,productId:'foreign'}))).status,404);assert.deepEqual(f.counts(),{charged:0,calls:0,created:0});});
test('portrait completion claims the second paid task once under concurrent polling',async()=>{
 let state='running',calls=0;const job={id:'j',organizationId:'org',status:'running',payload:{mode:'presenter',stage:'portrait',portraitTaskId:'portrait',productImage:'https://example.com/guitar.jpg',productInfo:'Actual',prompt:'Actual script',duration:10,cost:536}};
 const prisma={job:{updateMany:async q=>{if(q.data.status==='starting'){if(state!=='running')return{count:0};state='starting';return{count:1};}return{count:1};},update:async q=>{state=q.data.status;return{...job,...q.data};},findUniqueOrThrow:async()=>({...job,status:state})}};
 const helper=load('lib/presenter/jobs.ts',{'@/lib/prisma':{prisma},'@/lib/video/runway':{getVideoTask:async()=>({status:'SUCCEEDED',output:['https://output.cloudfront.net/portrait.png']}),validRunwayOutput:()=>true,createPresenterVideo:async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,5));return{id:'presenter-task'};},RunwayError:class extends Error{}},'@/lib/video/jobs':{failVideo:async()=>{throw new Error('Unexpected refund');}}});
 await Promise.all([helper.refreshPortrait(job),helper.refreshPortrait(job)]);assert.equal(calls,1);assert.equal(state,'running');
});
test('uncertain presenter request is retained without automatic regeneration or refund',async()=>{
 let saved,refunded=0,calls=0;const job={id:'j',payload:{duration:5,cost:280,productImage:'https://example.com/guitar.jpg',productInfo:'Actual',prompt:'Actual script'}};
 const helper=load('lib/presenter/jobs.ts',{'@/lib/prisma':{prisma:{job:{update:async q=>{saved=q.data;return{...job,...saved};},findUniqueOrThrow:async()=>({...job,...saved})}}},'@/lib/video/runway':{createPresenterVideo:async()=>{calls++;throw new Error('Timeout');},RunwayError:class extends Error{}},'@/lib/video/jobs':{failVideo:async()=>refunded++}});
 const result=await helper.startPresenter(job,'https://example.com/person.jpg');assert.equal(result.status,'uncertain');assert.equal(calls,1);assert.equal(refunded,0);
});
test('studio pages guide master accounts with no selected workspace instead of throwing',async()=>{
 const helper=load('lib/studio/page-context.ts',{'@/lib/auth/context':{tenantContext:async()=>{throw new Error('NO_WORKSPACE');}},'@/lib/admin/context':{superAdminContext:async()=>({id:'master'})}});const result=await helper.studioPageContext();assert.equal(result.context,null);assert.equal(result.recovery.href,'/admin');assert.equal(result.recovery.action,'Choose a workspace');
});
test('studio pages guide normal accounts to onboarding and retain unexpected errors',async()=>{
 const helper=load('lib/studio/page-context.ts',{'@/lib/auth/context':{tenantContext:async()=>{throw new Error('NO_WORKSPACE');}},'@/lib/admin/context':{superAdminContext:async()=>{throw new Error('FORBIDDEN');}}});assert.equal((await helper.studioPageContext()).recovery.href,'/onboarding');const broken=load('lib/studio/page-context.ts',{'@/lib/auth/context':{tenantContext:async()=>{throw new Error('DATABASE_UNAVAILABLE');}},'@/lib/admin/context':{superAdminContext:async()=>({})}});await assert.rejects(()=>broken.studioPageContext(),/DATABASE_UNAVAILABLE/);
});
test('public video readiness exposes only connection flags, never credentials',async()=>{
 const names=['RUNWAY_PRODUCTION_API_KEY','RUNWAY_API_KEY','BLOB_READ_WRITE_TOKEN'];const saved=names.map(key=>process.env[key]);
 try{names.forEach(key=>delete process.env[key]);const route=load('app/api/video/availability/route.ts',{'next/server':{NextResponse:{json:(body,options)=>({body,options})}},'@/lib/video/runway':{runwayConfigured:()=>Boolean((process.env.RUNWAY_PRODUCTION_API_KEY||process.env.RUNWAY_API_KEY)&&process.env.BLOB_READ_WRITE_TOKEN)}});assert.equal((await route.GET()).body.available,false);process.env.RUNWAY_PRODUCTION_API_KEY='test-private-key';process.env.BLOB_READ_WRITE_TOKEN='test-private-storage';const response=await route.GET();assert.equal(response.body.available,true);assert.deepEqual(Object.keys(response.body).sort(),['available','runwayConnected','storageConnected']);assert.ok(!JSON.stringify(response).includes('test-private'));assert.equal(response.options.headers['Cache-Control'],'no-store');}finally{names.forEach((key,i)=>{if(saved[i]===undefined)delete process.env[key];else process.env[key]=saved[i];});}
});
