// Hosted CI only: provider calls are mocked, so this test spends no credits.
const {chromium}=require('playwright');const esbuild=require('esbuild');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const http=require('node:http');const assert=require('node:assert/strict');
const repo=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(os.tmpdir(),'presenter-browser-'));let browser,server;const requests=[];
const fixture={configured:true,credits:2000,jobs:[],products:[{id:'guitar-a',name:'Website guitar',description:'Verified cedar top.',imageUrl:'/product.svg'}],posts:[{id:'post-a',headline:'Our collection'}]};
const photo='<svg xmlns="http://www.w3.org/2000/svg" width="240" height="320"><rect width="240" height="320" fill="#ddd"/><ellipse cx="120" cy="210" rx="65" ry="80" fill="#b58c55"/><rect x="110" y="25" width="20" height="180" fill="#614520"/></svg>';
(async()=>{
 fs.writeFileSync(path.join(output,'entry.tsx'),`import React from 'react';import UseCampaignVideo from ${JSON.stringify(repo+'/components/UseCampaignVideo')};import {createRoot} from 'react-dom/client';import PresenterStudio from ${JSON.stringify(repo+'/app/studio/presenters/PresenterStudio')};import ${JSON.stringify(repo+'/app/globals.css')};createRoot(document.getElementById('root')!).render(<><UseCampaignVideo assetId="clip" contentItemId="post-a" selected={false}/><PresenterStudio campaigns={[{id:'demo',title:'Demo campaign'}]} initialCampaignId="" initialContentItemId="post-a"/></>);`);
 await esbuild.build({entryPoints:[path.join(output,'entry.tsx')],bundle:true,outfile:path.join(output,'app.js'),nodePaths:[repo+'/node_modules'],jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'alias',setup(b){b.onResolve({filter:/^next\/navigation$/},()=>({path:'navigation',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:'export const useRouter=()=>({refresh(){window.__refresh=true},push(url){window.__navigation=url}});',loader:'js'}));b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+'.ts')}));}}]});
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/video/select'){res.statusCode=409;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:'This post already has a scheduled publishing entry.'}));return;}if(url.pathname==='/api/video/draft'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({campaignId:'demo',contentItemId:'new-draft'}));return;}if(url.pathname==='/api/video/presenter/products'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({products:[...fixture.products,{id:'website-b',websiteOnly:true,name:'Second guitar',imageUrl:'/product.svg'},{id:'website-c',websiteOnly:true,name:'Third guitar',imageUrl:'/product.svg'}]}));return;}if(url.pathname==='/api/video/presenter'){res.setHeader('Content-Type','application/json');if(req.method==='POST'){let body='';req.on('data',part=>body+=part);req.on('end',()=>{const data=JSON.parse(body);requests.push(data);res.end(JSON.stringify({job:{id:data.requestId,status:'succeeded',progress:100,cost:296,videoUrl:'/fixture.mp4',campaignId:data.campaignId,contentItemId:data.contentItemId}}));});return;}res.end(JSON.stringify(url.searchParams.has('campaignId')?fixture:{...fixture,products:[],posts:[]}));return;}if(url.pathname==='/product.svg'){res.setHeader('Content-Type','image/svg+xml');res.end(photo);return;}if(url.pathname==='/fixture.mp4'){res.statusCode=204;res.end();return;}if(['/app.js','/app.css'].includes(url.pathname)){res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript':'text/css');res.end(fs.readFileSync(path.join(output,url.pathname.slice(1))));return;}res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><link rel="stylesheet" href="/app.css"></head><body class="public-page"><main id="root"></main><script src="/app.js"></script></body></html>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+server.address().port;await page.goto(url);
 await page.getByRole('button',{name:'Use video for this post',exact:true}).click();await page.getByRole('alert').filter({hasText:'scheduled publishing entry'}).waitFor();await page.getByRole('button',{name:'Create a new draft with this video',exact:true}).click();await page.waitForFunction(()=>window.__navigation==='/campaigns/demo#post-new-draft');
 await page.getByLabel('Campaign',{exact:true}).selectOption('demo');await page.getByLabel('Website product',{exact:true}).selectOption('guitar-a');assert.equal(await page.getByLabel('Product name',{exact:true}).inputValue(),'Website guitar');assert.equal(await page.getByLabel('Verified product details').inputValue(),'Verified cedar top.');assert.match(await page.getByLabel('Spoken script').inputValue(),/Website guitar/);await page.getByRole('img',{name:'Selected product reference'}).waitFor();assert.equal(await page.getByLabel('Save clip to post').inputValue(),'post-a');
 await page.getByRole('button',{name:'Pick products for me',exact:true}).click();await page.getByRole('button',{name:'Pick again',exact:true}).waitFor();assert.equal(await page.locator('.presenter-choices article').count(),3);assert.equal(requests.length,0);await page.getByLabel('How many choices?').selectOption('2');await page.getByRole('button',{name:'Pick again',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.presenter-choices article').length===2);await page.locator('.presenter-choices article').last().getByRole('button').click();assert.equal(await page.locator('.presenter-choices button[aria-pressed="true"]').count(),1);await page.getByLabel('Website product',{exact:true}).selectOption('guitar-a');
 const generate=page.getByRole('button',{name:/^Generate presenter/});await page.getByText('536 Rumi credits',{exact:true}).waitFor();assert.equal(await generate.isDisabled(),true);await page.getByLabel('Clip length').selectOption('5');await page.getByText('296 Rumi credits',{exact:true}).waitFor();assert.equal(await generate.isDisabled(),true);await page.getByLabel('I approve the 296 credit cost and have permission to use these photos.').check();assert.equal(await generate.isEnabled(),true);await generate.click();await page.getByRole('heading',{name:'Presenter draft',exact:true}).waitFor();await page.getByRole('link',{name:'Use in reel editor',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'Use in reel editor',exact:true}).getAttribute('href'),'/studio/reels?campaignId=demo&contentItemId=post-a');await page.getByText('The clip is saved to its campaign post for review. It has not been published.').waitFor();assert.equal(requests.length,1);assert.equal(requests[0].consent,true);assert.equal(requests[0].duration,5);assert.equal(requests[0].productId,'guitar-a');assert.equal(requests[0].contentItemId,'post-a');assert.equal(requests[0].campaignId,'demo');assert.deepEqual(errors,[]);
 const disconnected=await browser.newPage();await disconnected.route('**/api/video/presenter*',route=>route.fulfill({json:{...fixture,configured:false}}));await disconnected.goto(url);await disconnected.getByText('Runway and private video storage need connecting before generation.').waitFor();assert.equal(await disconnected.getByRole('button',{name:/^Generate presenter/}).isDisabled(),true);await disconnected.close();
 const failed=await browser.newPage();await failed.route('**/api/video/presenter*',route=>route.fulfill({status:500,json:{error:'Presenter studio could not load. Try again.'}}));await failed.goto(url);await failed.getByRole('alert').filter({hasText:'Presenter studio could not load'}).waitFor();assert.equal(await failed.getByText('Runway and private video storage need connecting before generation.').count(),0);assert.equal(await failed.getByRole('button',{name:/^Generate presenter/}).isDisabled(),true);await failed.close();
 console.log('PASS: presenter campaign/post ownership fields, imported website product/photo/script, length-dependent credit price, required consent, mocked generation draft and original-post reel link, visible missing setup and load failure. No paid generation or publishing.');
})().catch(e=>{console.error(e);console.error('::error::'+String(e.stack||e).replace(/%/g,'%25').replace(/\r/g,'%0D').replace(/\n/g,'%0A'));process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
