// Runs in CI with an isolated browser, synthetic media and mocked campaign data.
const { chromium } = require('playwright');
const esbuild = require('esbuild');
const fs = require('node:fs'); const path = require('node:path'); const os = require('node:os'); const http = require('node:http'); const { spawnSync } = require('node:child_process'); const assert = require('node:assert/strict');
const repo=path.resolve(__dirname,'..'), output=fs.mkdtempSync(path.join(os.tmpdir(),'reel-browser-')); let browser, server; const uploads=new Map(), mutations=[]; let weeklyRequest;
const image='<svg xmlns="http://www.w3.org/2000/svg" width="720" height="1280"><rect width="720" height="1280" fill="#597450"/><ellipse cx="360" cy="760" rx="190" ry="260" fill="#e1b260"/><rect x="325" y="140" width="70" height="650" fill="#563a21"/><circle cx="360" cy="730" r="65" fill="#132342"/></svg>';
function verify(file) {
 const result=spawnSync('ffprobe',['-v','error','-count_frames','-show_streams','-of','json',file],{encoding:'utf8'}); assert.equal(result.status,0,result.stderr);
 const streams=JSON.parse(result.stdout).streams, video=streams.find(s=>s.codec_type==='video'); assert.equal(video.width,1080); assert.equal(video.height,1920); assert.ok(Number(video.nb_read_frames)>100,'Export must contain the timeline, not one frozen frame');assert.ok(streams.some(s=>s.codec_type==='audio'),'Soundtrack must be recorded');
 const decoded=spawnSync('ffmpeg',['-v','error','-i',file,'-f','null','-'],{encoding:'utf8'});assert.equal(decoded.status,0,decoded.stderr);
 const audio=spawnSync('ffmpeg',['-i',file,'-vn','-af','volumedetect','-f','null','-'],{encoding:'utf8'});assert.match(audio.stderr,/max_volume: -?[0-9.]+ dB/,'Sound must contain audio rather than silence');
}
(async()=>{
 const fixture=spawnSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','color=c=blue:s=720x1280:r=30','-f','lavfi','-i','sine=frequency=600:sample_rate=44100','-t','2','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',path.join(output,'clip.mp4')]);assert.equal(fixture.status,0,String(fixture.stderr));
 fs.writeFileSync(path.join(output,'entry.tsx'),`import React from 'react';import {createRoot} from 'react-dom/client';import ReelEditor from ${JSON.stringify(repo+'/app/studio/reels/ReelEditor')};import ${JSON.stringify(repo+'/app/globals.css')};createRoot(document.getElementById('root')!).render(<ReelEditor initialCampaignId="" initialContentItemId="post-a"/>);`);
 await esbuild.build({entryPoints:[path.join(output,'entry.tsx')],bundle:true,outfile:path.join(output,'app.js'),nodePaths:[repo+'/node_modules'],jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},plugins:[{name:'blob-fixture',setup(b){b.onResolve({filter:/^@vercel\/blob\/client$/},()=>({path:'blob-fixture',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({loader:'js',contents:`export async function upload(pathname,blob,options){const response=await fetch('/fixture-upload?pathname='+encodeURIComponent(pathname),{method:'POST',headers:{'Content-Type':blob.type,'X-Client-Payload':encodeURIComponent(options.clientPayload)},body:blob});if(!response.ok)throw new Error('Fixture upload failed');return {pathname,url:'/fixture-video?pathname='+encodeURIComponent(pathname)};}`}));}},{name:'alias',setup(b){b.onResolve({filter:/^@\//},a=>({path:path.join(repo,a.path.slice(2)+'.ts')}));}}]});
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(req.method==='POST'){mutations.push(url.pathname);if(url.pathname==='/api/reels/week'){let body='';req.on('data',part=>body+=part);req.on('end',()=>{weeklyRequest=JSON.parse(body);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({days:weeklyRequest.days.map((day,i)=>({...day,contentItemId:'weekly-post-'+i}))}));});return;}if(url.pathname==='/fixture-upload'){const parts=[];req.on('data',part=>parts.push(part));req.on('end',()=>{uploads.set(url.searchParams.get('pathname'),{bytes:Buffer.concat(parts),type:req.headers['content-type'],payload:JSON.parse(decodeURIComponent(req.headers['x-client-payload']))});res.end('{}');});return;}}if(url.pathname==='/api/reels/upload'){const found=uploads.get(url.searchParams.get('pathname'));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(found?{assetId:'asset-'+found.payload.contentItemId}:{}));return;}if(url.pathname==='/api/reels/project'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(url.searchParams.has('campaignId')?{organizationId:'org-a',campaign:{id:'demo',title:'Find your next guitar'},brand:{name:'Rumi Guitars',color:'#132342',accent:'#dec184',website:'rumiguitars.com'},posts:[{id:'post-a',headline:'Find your next guitar',caption:''}],sources:[{id:'image-a',src:'/photo.svg',kind:'image',contentItemId:'post-a'}]}:{campaigns:[{id:'demo',title:'Demo'}]}));return;}if(url.pathname==='/photo.svg'){res.setHeader('Content-Type','image/svg+xml');res.end(image);return;}if(['/app.js','/app.css'].includes(url.pathname)){res.setHeader('Content-Type',url.pathname.endsWith('.js')?'text/javascript':'text/css');res.end(fs.readFileSync(path.join(output,url.pathname.slice(1))));return;}res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><link rel="stylesheet" href="/app.css"></head><body class="public-page"><main id="root"></main><script src="/app.js"></script></body></html>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.getByLabel('Campaign',{exact:true}).selectOption('demo');await page.getByText('Closing screen',{exact:true}).waitFor();await page.getByLabel('Visual style').selectOption('gallery');await page.getByLabel('Supporting caption').fill('Explore the collection at Rumi Guitars.');await page.getByRole('button',{name:'Save draft in this browser'}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).waitFor();await page.reload();await page.getByLabel('Campaign',{exact:true}).selectOption('demo');await page.getByRole('status').filter({hasText:'saved draft was restored'}).waitFor();assert.equal(await page.getByLabel('Supporting caption').inputValue(),'Explore the collection at Rumi Guitars.');
 await page.getByRole('button',{name:'Export finished reel'}).click();await page.getByRole('link',{name:'Download finished reel'}).waitFor({timeout:45000});const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download finished reel'}).click()]);const file=path.join(output,download.suggestedFilename());await download.saveAs(file);verify(file);
 await page.getByLabel('Upload a photo or real / AI presenter clip').setInputFiles(path.join(output,'clip.mp4'));await page.getByLabel('Keep audio from the video clips').check();await page.getByLabel('Visual style').selectOption('cinematic');await page.getByRole('button',{name:'Export finished reel'}).click();await page.getByRole('link',{name:'Download finished reel'}).waitFor({timeout:45000});const [clip]=await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'Download finished reel'}).click()]);const clipFile=path.join(output,'presenter-'+clip.suggestedFilename());await clip.saveAs(clipFile);verify(clipFile);
 await page.getByRole('button',{name:'Export finished reel'}).click();await page.getByRole('button',{name:'Cancel export'}).click();await page.getByRole('status').filter({hasText:'Export cancelled'}).waitFor({timeout:15000});assert.deepEqual(errors,[]);
 await page.reload();await page.getByLabel('Campaign',{exact:true}).selectOption('demo');await page.getByRole('status').filter({hasText:'saved draft was restored'}).waitFor();
 const weekly=page.locator('section').filter({has:page.getByRole('heading',{name:'Create a week of reels',exact:true})});await weekly.getByLabel('First day').fill('2026-10-05');await weekly.getByRole('button',{name:'Plan seven days'}).click();assert.equal(await weekly.locator('details').count(),7);
 const summaries=await weekly.locator('summary').allTextContents();for(let i=0;i<7;i++)assert.ok(summaries[i].includes('2026-10-'+String(5+i).padStart(2,'0')));
 const layouts=[];for(let i=0;i<7;i++){const day=weekly.locator('details').nth(i);await day.locator('summary').click();layouts.push(await day.getByLabel('Daily layout').inputValue());assert.ok((await day.getByLabel('Daily caption').inputValue()).includes('Rumi Guitars'));}assert.equal(new Set(layouts).size,3);
 await weekly.locator('details').first().getByLabel('Daily caption').fill('Weekly caption reviewed by the owner.');await weekly.getByRole('button',{name:'Create and save seven reels'}).click();await weekly.getByRole('status').filter({hasText:'All seven reels are saved'}).waitFor({timeout:180000});assert.equal(uploads.size,7);assert.equal(weeklyRequest.days.length,7);assert.equal(weeklyRequest.days[0].caption,'Weekly caption reviewed by the owner.');assert.equal(weeklyRequest.campaignId,'demo');assert.equal(new Set(weeklyRequest.days.map(day=>day.headline)).size,7);
 for(let i=0;i<7;i++){const day=weekly.locator('details').nth(i);const [download]=await Promise.all([page.waitForEvent('download'),day.getByRole('link',{name:/^Download /}).click()]);const target=path.join(output,'weekly-'+download.suggestedFilename());await download.saveAs(target);verify(target);const saved=[...uploads.values()].find(value=>value.payload.contentItemId==='weekly-post-'+i);assert.ok(saved.bytes.length>10000);assert.deepEqual(saved.bytes,fs.readFileSync(target),'Campaign upload must contain the actual downloadable reel');assert.equal(saved.payload.campaignId,'demo');assert.ok(saved.payload.duration>=7);assert.match(await day.locator('summary').textContent(),/Saved/);}
 assert.deepEqual(mutations.filter(name=>name!=='/fixture-upload'),['/api/reels/week'],'Only draft creation is requested; no publication or scheduling');assert.deepEqual(errors,[]);
 const failedPage=await browser.newPage();await failedPage.route('**/api/reels/project*',route=>route.fulfill({status:500,json:{error:'Could not load campaigns. Try again.'}}));await failedPage.goto('http://127.0.0.1:'+server.address().port);await failedPage.getByRole('status').filter({hasText:'Could not load campaigns'}).waitFor();await failedPage.getByRole('button',{name:'Refresh campaigns'}).click();await failedPage.getByRole('status').filter({hasText:'Could not load campaigns'}).waitFor();await failedPage.close();
 const emptyPage=await browser.newPage();await emptyPage.route('**/api/reels/project*',route=>route.fulfill({json:{campaigns:[]}}));await emptyPage.goto('http://127.0.0.1:'+server.address().port);await emptyPage.getByRole('heading',{name:'No campaigns available in this workspace'}).waitFor();await emptyPage.getByRole('link',{name:'Create a campaign',exact:true}).waitFor();await emptyPage.close();
 console.log('PASS: campaign selection, visible fetch errors and empty-workspace guidance; browser draft recovery, vertical video encoding, non-silent soundtrack, imported presenter clip, cancellation, seven varied weekly drafts with real video/audio uploads and no automatic publishing, and no page errors.');
})().catch(e=>{console.error(e);console.error('::error::'+String(e.stack||e).replace(/%/g,'%25').replace(/\r/g,'%0D').replace(/\n/g,'%0A'));process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
