const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function setup({missingAsset=false,channel='channel',interrupt=false,certified=true}={}) {
 const jobs=new Map(),calls=[],reads=[],uploads=[]; const options={certified,madeForKids:false,containsSyntheticMedia:true,connectionId:'connection'};
 const prisma={job:{findFirst:async({where})=>where.id.startsWith('youtube_settings_')?{payload:options}:jobs.get(where.id)||null,create:async({data})=>{if(jobs.has(data.id))throw Error('duplicate');jobs.set(data.id,{...data});return data},update:async({where,data})=>{Object.assign(jobs.get(where.id),data)}},mediaAsset:{findFirst:async({where})=>{reads.push(where);return missingAsset?null:{id:'asset',organizationId:'org',contentItemId:'post'}}},socialConnection:{findFirst:async({where})=>{reads.push(where);return {id:'connection',organizationId:'org',externalId:'channel',encryptedToken:'secret'}}},contentItem:{findFirst:async()=>({headline:'Actual title'})}};
 const deps={'@/lib/prisma':{prisma},'@/lib/video/media':{videoBytes:async asset=>{uploads.push(asset.id);return {bytes:Buffer.from('actual-video-bytes'),contentType:'video/mp4'}}},'./youtube':{youtubeAccessToken:async()=> 'token',youtubeUploadUrl:url=>{assert.equal(url,'https://www.googleapis.com/upload/youtube/v3/videos?session=test');return url}}};
 const fetch=async(url,init={})=>{calls.push({url,init});if(url.includes('/channels?'))return Response.json({items:[{id:channel}]});if(init.method==='POST')return new Response(null,{headers:{location:'https://www.googleapis.com/upload/youtube/v3/videos?session=test'}});if(interrupt)throw Error('lost response');return Response.json({id:'video',snippet:{channelId:'channel'},status:{privacyStatus:'private'}})};
 const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(__dirname+'/../lib/publishing/youtube-campaign.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports,require:n=>deps[n],fetch,AbortSignal,Uint8Array});
 return {run:module.exports.publishYouTubeCampaign,jobs,calls,reads,uploads};
}
const input={assetId:'asset',organizationId:'org',contentItemId:'post',publishJobId:'scheduled',externalAccountId:'channel',caption:'Actual caption'};
test('campaign upload uses selected bytes, metadata, private visibility and disclosure; repeat jobs reuse receipt',async()=>{const s=setup();assert.equal((await s.run(input)).ok,true);const post=s.calls.find(x=>x.init.method==='POST');const metadata=JSON.parse(post.init.body);assert.equal(metadata.snippet.title,'Actual title');assert.equal(metadata.snippet.description,'Actual caption');assert.equal(metadata.status.privacyStatus,'private');assert.equal(metadata.status.containsSyntheticMedia,true);assert.equal(Buffer.from(s.calls.find(x=>x.init.method==='PUT').init.body).toString(),'actual-video-bytes');const count=s.calls.length;assert.equal((await s.run({...input,publishJobId:'different'})).externalId,'video');assert.equal(s.calls.length,count);assert.equal(s.reads[0].organizationId,'org');assert.equal(s.reads[0].contentItemId,'post')});
test('missing consent or foreign/unavailable asset never uploads',async()=>{for(const options of [{certified:false},{missingAsset:true}]){const s=setup(options);assert.equal((await s.run(input)).ok,false);assert.equal(s.calls.length,0);assert.equal(s.uploads.length,0)}});
test('channel mismatch prevents upload initialization',async()=>{const s=setup({channel:'foreign'});assert.equal((await s.run(input)).ok,false);assert.equal(s.calls.length,1);assert.equal(s.jobs.size,0)});
test('ambiguous upload is never submitted again, including from a new publish job',async()=>{const s=setup({interrupt:true});assert.equal((await s.run(input)).retryable,false);const count=s.calls.length;assert.equal((await s.run({...input,publishJobId:'different'})).ok,false);assert.equal(s.calls.length,count);assert.equal([...s.jobs.values()][0].status,'uncertain')});
