"use client";
import {useState} from "react";
import {portalMedia,portalBlockers,type ReviewItem} from "@/lib/agency/portal-review";
export default function CampaignApprovalReview({token,items,allowComments,status}:{token:string;items:ReviewItem[];allowComments:boolean;status:string}){
 const [comment,setComment]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState(''),[failedMedia,setFailedMedia]=useState<string[]>([]),[reviewed,setReviewed]=useState(false);
 const blocked=portalBlockers(items).length>0||failedMedia.length>0||items.length===0;
 async function respond(decision:"approved"|"changes_requested"){
  setBusy(true);setError('');
  try{const response=await fetch('/api/approvals/respond',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,decision,comment:allowComments?comment:undefined})});const value=await response.json();if(!response.ok)throw new Error(typeof value.error==='string'?value.error:'Could not save your response.');setResult(decision==='approved'?'Campaign approved. This does not publish or schedule any posts.':'Your request for changes has been saved.');}
  catch(e){setError(e instanceof Error?e.message:'Could not save your response.');}finally{setBusy(false);}
 }
 return <><p>{items.length} campaign drafts to review.</p><div className="portalitems">{items.map((item,index)=>{const media=portalMedia(item);return <article className="card" key={item.id}><span className="eyebrow">{index+1} of {items.length} · {item.platform} · {item.type}</span><h3>{item.headline}</h3><p style={{whiteSpace:'pre-wrap'}}>{item.caption}</p>{media.url&&(media.kind==='video'?<video src={media.url} controls preload="metadata" style={{maxWidth:'100%'}} onError={()=>setFailedMedia(s=>s.includes(item.id)?s:[...s,item.id])}/>:<img src={media.url} alt={item.headline||'Campaign creative'} loading="lazy" style={{maxWidth:'100%'}} onError={()=>setFailedMedia(s=>s.includes(item.id)?s:[...s,item.id])}/>)}{media.blocked&&<p role="status">This media cannot be reviewed through this link yet. Ask the campaign owner to provide reviewable media or review it in the workspace before approval.</p>}</article>;})}</div><section className="decision"><h2>Campaign response</h2>{result?<p role="status">{result}</p>:status!=='pending'?<p role="status">This approval has already been completed: {status.replaceAll('_',' ')}.</p>:<><p>Review every draft above before approving. Approval records your decision; it does not schedule or publish posts.</p>{blocked&&<p role="alert">Approval is unavailable because some media cannot be reviewed, or there are no drafts. You can still request changes.</p>}{allowComments&&<label>Feedback<textarea value={comment} maxLength={2000} disabled={busy} onChange={e=>setComment(e.target.value)}/></label>}<label><input type="checkbox" checked={reviewed} disabled={busy||blocked} onChange={e=>setReviewed(e.target.checked)}/> I have reviewed all {items.length} drafts and their media.</label><div><button className="button" disabled={busy||blocked||!reviewed} onClick={()=>respond('approved')}>Approve Campaign</button><button disabled={busy} onClick={()=>respond('changes_requested')}>Request Changes</button></div>{error&&<p role="alert">{error}</p>}</>}</section></>;
}
