"use client";
import {useEffect,useRef,useState} from "react";
import {presenterCost} from "@/lib/presenter/plan";
type Job={id:string;status:string;progress:number;error?:string;videoUrl?:string;cost:number;campaignId?:string;contentItemId?:string};
type Product={id:string;name:string;description?:string;imageUrl?:string};
export default function PresenterStudio({campaigns,initialCampaignId,initialContentItemId}:{campaigns:{id:string;title:string}[];initialCampaignId:string;initialContentItemId:string}){
 const [campaignId,setCampaignId]=useState(initialCampaignId),[itemId,setItemId]=useState(initialContentItemId),[posts,setPosts]=useState<{id:string;headline?:string}[]>([]),[products,setProducts]=useState<Product[]>([]),[productId,setProductId]=useState(""),[productImage,setProductImage]=useState(""),[name,setName]=useState(""),[details,setDetails]=useState(""),[characterImage,setCharacterImage]=useState(""),[look,setLook]=useState("neutral"),[script,setScript]=useState(""),[duration,setDuration]=useState<5|10|15>(10),[consent,setConsent]=useState(false),[credits,setCredits]=useState(0),[configured,setConfigured]=useState(false),[connectionLoaded,setConnectionLoaded]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[jobs,setJobs]=useState<Job[]>([]),[current,setCurrent]=useState<Job|null>(null);const request=useRef("");const cost=presenterCost(duration,!characterImage);
 useEffect(()=>{let active=true;setLoading(true);setConnectionLoaded(false);setError("");setProducts([]);setPosts([]);fetch(`/api/video/presenter${campaignId?`?campaignId=${encodeURIComponent(campaignId)}`:""}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load studio.");if(active){setCredits(d.credits);setConfigured(d.configured);setConnectionLoaded(true);setJobs(d.jobs||[]);setProducts(d.products||[]);setPosts(d.posts||[]);setItemId(previous=>(d.posts||[]).some((p:{id:string})=>p.id===previous)?previous:d.posts?.[0]?.id||"");}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[campaignId]);
 useEffect(()=>{if(!current||!["running","saving","starting"].includes(current.status))return;const id=setInterval(async()=>{try{const r=await fetch(`/api/video/presenter?jobId=${current.id}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setCurrent(d.job);}catch(e){setError(e instanceof Error?e.message:"Status delayed.");}},16000);return()=>clearInterval(id);},[current]);
 async function photo(file:File|undefined,character=false){if(!file)return;if(file.size>1_000_000||!["image/png","image/jpeg","image/webp"].includes(file.type)){setError("Choose a PNG, JPEG or WebP photo under 1 MB.");return;}try{const uri=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("Could not read photo."));reader.readAsDataURL(file);});if(character)setCharacterImage(uri);else setProductImage(uri);setError("");}catch(e){setError(e instanceof Error?e.message:"Photo unavailable.");}}
 async function generate(){setBusy(true);setError("");request.current ||=crypto.randomUUID();try{const r=await fetch("/api/video/presenter",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:request.current,campaignId,contentItemId:itemId,productId:productId||undefined,productImage:productImage||undefined,productName:name,productDetails:details,characterImage:characterImage||undefined,look,script,duration,consent})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not start presenter.");setCurrent(d.job);setJobs(previous=>[d.job,...previous.filter(j=>j.id!==d.job.id)]);const balance=await fetch("/api/video/presenter").then(r=>r.json()).catch(()=>null);if(balance)setCredits(balance.credits);}catch(e){setError(e instanceof Error?e.message:"Request failed. Retry reuses the same request ID.");}finally{setBusy(false);}}
 function selectProduct(id:string){setProductId(id);setProductImage("");const product=products.find(p=>p.id===id);if(product){setName(product.name);setDetails(product.description?.slice(0,1800)||"");setScript(`Meet ${product.name}. Take a closer look at the photos and details on our website, and contact us with your questions.`);}}
 async function check(job:Job){try{const r=await fetch(`/api/video/presenter?jobId=${job.id}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setCurrent(d.job);}catch(e){setError(e instanceof Error?e.message:"Could not check video.");}}
 const locked=busy||Boolean(current&&["starting","running","saving","uncertain"].includes(current.status));
 return <><div className="eyebrow">AI PRESENTER STUDIO</div><h1>Introduce your actual product.</h1><p>Create a talking presenter using your product photo, then add the clip to a finished reel. Check the product’s appearance and spoken details before approving it.</p><a href="/studio/reels">Back to reel editor</a>{error&&<p role="alert">{error}</p>}{loading&&<p role="status">Loading campaigns and products…</p>}{!campaigns.length&&<section className="card"><h2>Create a campaign first</h2><a className="button" href="/campaigns">Open campaigns</a></section>}
 <section className="card" style={{marginTop:24}}><fieldset disabled={locked||loading} style={{border:0,padding:0}}><label htmlFor="presenter-campaign">Campaign</label><select id="presenter-campaign" value={campaignId} onChange={e=>{setCampaignId(e.target.value);setProductId("");setProductImage("");}}><option value="">Choose campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><label htmlFor="presenter-post">Save clip to post</label><select id="presenter-post" value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Choose post</option>{posts.map(p=><option key={p.id} value={p.id}>{p.headline||"Untitled post"}</option>)}</select>{campaignId&&!loading&&!posts.length&&<p>This campaign needs a draft post before you can save a presenter clip.</p>}
 <label htmlFor="presenter-product">Website product</label><select id="presenter-product" value={productId} onChange={e=>selectProduct(e.target.value)}><option value="">Use an uploaded product photo</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><label>Actual product photo · optional replacement</label><input aria-label="Actual product photo" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>photo(e.target.files?.[0])}/>{(productImage||products.find(p=>p.id===productId)?.imageUrl)&&<img alt="Selected product reference" src={productImage||products.find(p=>p.id===productId)?.imageUrl} style={{width:150,height:180,objectFit:"contain"}}/>}<label htmlFor="presenter-name">Product name</label><input id="presenter-name" maxLength={180} value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="presenter-details">Verified product details</label><textarea id="presenter-details" maxLength={1800} value={details} onChange={e=>setDetails(e.target.value)}/><label htmlFor="presenter-look">Presenter</label><select id="presenter-look" value={look} onChange={e=>setLook(e.target.value)}><option value="neutral">Fictional presenter</option><option value="woman">Fictional woman</option><option value="man">Fictional man</option></select><label>Or upload a presenter photo you have permission to use</label><input aria-label="Presenter reference photo" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>photo(e.target.files?.[0],true)}/>{characterImage&&<><img alt="Presenter reference" src={characterImage} style={{width:110,height:140,objectFit:"contain"}}></img><button type="button" onClick={()=>setCharacterImage("")}>Use fictional presenter instead</button></>}
 <label htmlFor="presenter-script">Spoken script</label><textarea id="presenter-script" maxLength={500} value={script} onChange={e=>setScript(e.target.value)} placeholder="A short introduction using verified facts."/><p>Keep the script brief: about 10 words for 5 seconds, 20 for 10 seconds or 30 for 15 seconds.</p><label htmlFor="presenter-duration">Clip length</label><select id="presenter-duration" value={duration} onChange={e=>setDuration(Number(e.target.value) as 5|10|15)}><option value={5}>5 seconds</option><option value={10}>10 seconds</option><option value={15}>15 seconds</option></select><p><strong>{cost} Rumi credits</strong> · {credits} available. {characterImage?"Uses your presenter reference.":"Includes creating a fictional presenter portrait."}</p>{credits<cost&&configured&&<p><a href="/billing">Add credits in Billing</a> before generating this clip.</p>}{connectionLoaded&&!configured&&!loading&&<p>Runway and private video storage need connecting before generation.</p>}<label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I approve the {cost} credit cost and have permission to use these photos.</label><button className="button" disabled={!configured||!consent||credits<cost||!itemId||!name||script.trim().length<10||(!productImage&&!products.find(p=>p.id===productId)?.imageUrl)} onClick={generate}>Generate presenter · {cost} credits</button></fieldset></section>
 {current&&<section className="card" style={{marginTop:24}}><h2>Presenter draft</h2><p role="status">{current.status} · {current.progress}%</p>{current.error&&<p>{current.error}</p>}<small>Request: {current.id}</small>{current.videoUrl&&<><video controls src={current.videoUrl} style={{width:"100%",maxWidth:300}}/><p><a href={current.videoUrl} download="presenter.mp4">Download clip</a> · <a href={`/studio/reels?campaignId=${current.campaignId||campaignId}&contentItemId=${current.contentItemId||itemId}`}>Use in reel editor</a></p><p>The clip is saved to its campaign post for review. It has not been published.</p></>}{["succeeded","failed"].includes(current.status)&&<button onClick={()=>{setCurrent(null);request.current="";setConsent(false);}}>Create another presenter</button>}</section>}
 {!!jobs.length&&<section className="card" style={{marginTop:24}}><h2>Recent presenter drafts</h2>{jobs.map(j=><p key={j.id}>{j.status} · {j.cost} credits <button onClick={()=>check(j)}>Open draft</button></p>)}</section>}</>;
}
